"""Unified analysis endpoint for text, voice, image, and camera inputs."""

from __future__ import annotations

import asyncio
import logging
import time
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status
from sqlalchemy.ext.asyncio import AsyncSession

from auth.dependencies import get_current_user
from auth.models import User
from config import UPLOAD_DIR
from database.db import get_db
from database.models import AdaptationLog, Event
from services.analyzer import analyze_image_with_groq
from services.cnn import detect_accident_objects
from services.voice import generate_voice_audio, trigger_department_calls


logger = logging.getLogger(__name__)

router = APIRouter()


async def _save_upload_file(upload_file: UploadFile, destination: Path) -> None:
    content = await upload_file.read()
    await asyncio.to_thread(destination.write_bytes, content)


def _analyze_text_payload(text: str) -> dict:
    normalized = (text or "").lower()
    severity = "Low"
    accident_type = "unknown"
    departments = ["police"]

    high_keywords = ["major", "critical", "severe", "serious", "multiple", "bleeding", "unconscious", "fire"]
    medium_keywords = ["injury", "accident", "crash", "collision", "ambulance", "emergency"]

    if any(keyword in normalized for keyword in high_keywords):
        severity = "High"
        departments = ["police", "hospital"]
    elif any(keyword in normalized for keyword in medium_keywords):
        severity = "Medium"
        departments = ["police", "hospital"]

    if "fire" in normalized:
        accident_type = "fire"
        departments = ["fire", "police"]
    elif any(keyword in normalized for keyword in ["injury", "ambulance", "medical", "hospital"]):
        accident_type = "medical"
    elif any(keyword in normalized for keyword in ["crash", "collision", "accident", "vehicle", "bike", "car", "truck"]):
        accident_type = "collision"

    return {
        "severity": severity,
        "accident_type": accident_type,
        "departments_to_call": departments,
        "voice_script": (
            "This is an automated alert from OnSpot. "
            f"A {accident_type} emergency has been reported. "
            f"Severity level is {severity}. "
            "Please dispatch response teams immediately."
        ),
        "confidence": 0.90,
        "severity_confidence": 0.85,
        "reasoning": "Rule-based text analysis",
        "recommended_action": "Dispatch departments and monitor event",
    }


@router.post("")
async def analyze_input(
    input_type: str = Form(...),
    text: str | None = Form(default=None),
    location: str | None = Form(default=None),
    file: UploadFile | None = File(default=None),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Accept text, voice, image, or camera input and run unified analysis."""

    start_time = time.time()
    event_id = str(uuid.uuid4())
    normalized_type = input_type.lower().strip()
    if normalized_type == "camera":
        normalized_type = "image"

    if normalized_type not in {"text", "voice", "image"}:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="input_type must be text, voice, image, or camera")

    try:
        analysis: dict
        image_path: str | None = None

        if normalized_type == "image":
            if file is None:
                raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Image input requires a file")
            uploaded_path = UPLOAD_DIR / f"{event_id}_{file.filename or 'upload.jpg'}"
            await _save_upload_file(file, uploaded_path)
            image_path = str(uploaded_path)
            cnn_result = await asyncio.to_thread(detect_accident_objects, image_path)
            analysis = await asyncio.to_thread(analyze_image_with_groq, image_path, cnn_result, location)
        else:
            # Voice input uses supplied transcript text when available.
            transcript = (text or "").strip()
            if not transcript:
                transcript = "Voice report received. Details were not provided."
            analysis = _analyze_text_payload(transcript)

        departments_to_call = list(dict.fromkeys(analysis.get("departments_to_call", [])))
        voice_script = analysis.get("voice_script", "Emergency alert generated by OnSpot")
        audio_file_path, _ = await generate_voice_audio(voice_script, event_id)

        call_status: dict[str, str] = {}
        if analysis.get("severity") in {"Medium", "High"} and departments_to_call:
            call_status = await trigger_department_calls(departments_to_call, voice_script, audio_file_path)

        response_time_ms = int((time.time() - start_time) * 1000)
        event = Event(
            id=uuid.UUID(event_id),
            user_id=current_user.id,
            input_type=normalized_type,
            image_path=image_path,
            location=location,
            severity=analysis.get("severity", "Medium"),
            accident_type=analysis.get("accident_type", "unknown"),
            departments_alerted=departments_to_call,
            voice_script=voice_script,
            audio_file_path=audio_file_path,
            call_status=call_status,
            ai_decision=analysis.get("reasoning", "Analysis completed"),
            status="completed",
            response_time_ms=response_time_ms,
            training_metadata={
                "detection_confidence": analysis.get("confidence", 0.0),
                "severity_confidence": analysis.get("severity_confidence", 0.0),
                "overall_confidence": round((analysis.get("confidence", 0.0) + analysis.get("severity_confidence", 0.0)) / 2, 2)
            }
        )
        db.add(event)
        await db.flush()

        adaptation_log = AdaptationLog(
            event_id=event.id,
            severity_predicted=analysis.get("severity", "Medium"),
            departments_called=departments_to_call,
            response_time_ms=response_time_ms,
            rule_version=1,
        )
        db.add(adaptation_log)
        await db.commit()

        return {
            "event_id": str(event.id),
            "input_type": normalized_type,
            "decision_result": {
                "severity": analysis.get("severity", "Medium"),
                "event_type": analysis.get("accident_type", "unknown"),
                "priority": "high" if analysis.get("severity") in {"High", "Medium"} else "normal",
                "departments_alerted": departments_to_call,
            },
            "route_details": {
                "location": location,
                "recommended_action": analysis.get("recommended_action", "Monitor and dispatch units"),
            },
            "alert_status": call_status,
            "status": "completed",
            "response_time_ms": response_time_ms,
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Unified analysis failed: %s", exc)
        try:
            await db.rollback()
        except Exception:
            pass
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Analysis pipeline failed") from exc
